### PR TITLE
update params for CGMPortfolio

### PR DESCRIPTION
**Pull request by MridulS**
After the update to ConsPortfolioModel to accept age varying riskyavg and riskystd, RiskyDstnFunc and RiskyDrawFunc lambda function aren't required as part of params. It should instead be `RiskyAvg`, `RiskyStd`

### CODE REVIEW

**Comment by mnwhite** [comment]
We do need to update the parameter files, but I don't think we need to put age-varying RiskyAvg and RiskyStd here at all, nor their XXXTrue variants.  It's an optional feature that isn't used here.  RiskyAvg = mu and RiskyStd = sigma would suffice.

**Comment by llorracc** [comment]
@mnwhite, just before your comment, I've just added some comments explaining a bit what is going on.  Could you edit as required for your proposed code revision?

**Comment by mnwhite** [comment]
Yeah, if you and Mridul agree that we shouldn't have complications where we
don't need them.

**Comment by MridulS** [comment]
+1 I’ll remove the age_varying stuff from base parameters

This should only swap in RiskyAvg and RiskyStd

**Comment by MridulS** [comment]
```
 # Make a [list] of beliefs about Mu and Std by age
# Allows beliefs to vary with age (and, depending on 
# implementation in simulation, potentially outcomes as well)
# For example, inexperience might cause low returns when young,
# and cognitive decline when old 
```

this should be in the documentation of ConsPortfolioModel not in the CGM portfolio REMARK

**Pull request merged**
