### PR TITLE
REMARK of DCEGM paper

### PR DESCRIPTION
**Pull request by pkofod**
This is a REMARK (or the beginning of one) of the DCEGM paper (see references in notebook).

It is a massively refactored version of the code that is in https://github.com/econ-ark/HARK/pull/206 . It's refactored to be general in the sense that it reuses code much more, and it now uses the functions that were introduced in https://github.com/econ-ark/HARK/pull/209 and the functions that will hopefully soon be merged in https://github.com/econ-ark/HARK/pull/226 . The functions from the two PRs are repeated in the third cell, because one PR is not merged yet, and the other PR is not yet part of an official release. **Most important of all**, it now properly inherits from existing HARK classes, so all the code for shocks etc is now gone.

@llorracc does Shujaat have a github handle I can @ ?

There is some text, and I want to clean up all the cells (it's still WIP). The last few cells show how Figure 2 and Figure 3 can be reproduced using the code (though I realize now, that the time periods don't match, I need to double check that.).

### CODE REVIEW

**Comment by pkofod** [comment]
@llorracc  One thing that crossed my mind is that the titles and names of folders have no system or coherent structure. Is there prior discussion about this I can find somewhere, or is it "something to be discussed"?

If REMARK is actually to be populated with many reproductions of results in papers (which I think would be valuable on many levels), it would be good to have a system or at least a website where you can easily look down the page and find a paper or theme you're interested in.

**Comment by llorracc** [comment]
@pkofod @DrDrij 

You are right that the REMARKs do not have any organization behind them at present.  Since there are only 3 or 4 so far that's not too much of a problem.  But I have given a very vague mission to Andrij (cc'd) to give some thought to how we might encompass the REMARKs and DemARKs and other content in a more systematic way.  I'd also like to integrate our content with the excellent stuff that QuantEcon has produced.  It's challenging to figure out how to allow all of this stuff to flourish on its own but still be able to tie the pieces together.  Tags!  Tags are the key to everything, I feel.

**Comment by pkofod** [comment]
> Tags! Tags are the key to everything, I feel.

Though this is well beyond my skills to implement, I agree. What would be helpful would just be some indication from some overview-page what a given remark was one. Could be many things, but things like "retirement", "housing", an abbreviation for the journal (year?), and so on would be nice.

I also agree with your statement that this is currently not an issue, but one could wish that 4 years from now, there were so many remarks that it was impossible to browse them without some guidance (say from tags).

**Comment by pkofod** [comment]
- Took Shujaat's comments into consideration
-  added some text thanking Thomas for providing figure scripts.
- I added text that explained the figures at the end.
- I added Zotero citations instead of my hand-rollen citations


@llorracc there's a thing I think we never discussed. What's the "NARK"-compliant name for the taste shock scale parameter? It's simply `sigma` right now.

**Comment by llorracc** [comment]
Shujaat and I have looked this over and it looks good.

**Comment by pkofod** [comment]
> Shujaat and I have looked this over and it looks good.

Great! Good to hear. When the new release of HARK is out, we can use some of the tools I've duplicated here, and we can discuss if more stuff needs to be done. We will eventually transition into using a more general purpose discrete choice tool from HARK, but that'll be later, and we can update this accordingly. 

I will say, that this PR uses the version of the tools here https://github.com/econ-ark/HARK/pull/242, so I hope that makes it in before the new release, or we will still have to duplicate code here.

**Comment by llorracc** [comment]
For Release Notes: A comprehensive reproduction of the results of the [DCEGM](https://github.com/econ-ark/DemARK/blob/master/notebooks/DCEGM-Upper-Envelope.ipynb) paper of Iskhakov, Jørgensen, Rust, and Schjerning, using the [dcegm.py](https://github.com/econ-ark/HARK/blob/master/HARK/dcegm.py) tool of the [Econ-ARK/HARK](https://github.com/econ-ark/HARK).  A brief [demonstration](https://github.com/econ-ark/DemARK/blob/master/notebooks/DCEGM-Upper-Envelope.ipynb) is available here. 

Iskhakov, F., Jørgensen, T.H., Rust, J., Schjerning, B., 2017. [The endogenous grid method for discrete-continuous dynamic choice models with (or without) taste shocks](https://qeconomics.org/ojs/index.php/qe/article/viewFile/441/434). Quantitative Economics 8, 317–365. https://doi.org/10.3982/QE643

**Pull request merged**
