### PR TITLE
add html PortfolioChoiceBlogPost

### PR DESCRIPTION
**Pull request by MridulS**
`jupyter nbconvert --to html PortfolioChoiceBlogPost.ipynb`

### CODE REVIEW

**Comment by llorracc** [comment]
Is the correct _complete_ workflow:
```
cd [root]/REMARK/REMARKs/PortfolioChoiceBlogPost
git checkout gh-pages
jupyter nbconvert --to html PortfolioChoiceBlogPost.ipynb
git add .
git commit -m 'Recompiled PortfolioChoiceBlogPost'
git push
```

**Comment by MridulS** [comment]
There is no need for git checkout gh-pages, GitHub is pulling in from the master branch.

**Comment by llorracc** [comment]
So if I've made some changes to the notebook and saved them locally, is this the correct workflow?

```
cd [root]/REMARK/REMARKs/PortfolioChoiceBlogPost
git checkout master
git add .
git commit 'Changes to PortfolioChoiceBlogPost'
jupyter nbconvert --to html PortfolioChoiceBlogPost.ipynb
git add .
git commit -m 'Recompiled PortfolioChoiceBlogPost'
git push
```

And after the push, when I go to econ-ark.github.io/REMARK/REMARKs/PortfolioChoiceBlogPost/PortfolioChoiceBlogPost.html

I should see the modifications instantiated?  Even though I didn't put the changes on the `gh-pages` branch?

**Comment by MridulS** [comment]
Yeah this will work, but you want see the changes on econ-ark.github.io/REMARK/REMARKs/PortfolioChoiceBlogPost/PortfolioChoiceBlogPost.html <http://econ-ark.github.io/REMARK/REMARKs/PortfolioChoiceBlogPost/PortfolioChoiceBlogPost.html> instantly as it takes some time for GitHub to update it. You can open the HTML file locally in any browser to see the changes.

**Comment by MridulS** [comment]
You won’t* see the changes instantly.

**Pull request merged**
