### PR TITLE
Add Ganong Noel

### PR DESCRIPTION
**Pull request by ganong123**
Consumer Spending During Unemployment Positive and Normative Implications

Supersedes #5

### CODE REVIEW

**Comment by ganong123** [comment]
FYI @llorracc @npalmer-professional

**Comment by mnwhite** [comment]
We aren't ignoring this PR-- just in AEA mode! I will be clearing out the
backlog of PRs here (and on HARK and DemARK) in February.

**Comment by mnwhite** [comment]
Handling this is now considered a priority item, @ganong123

**Comment by llorracc** [comment]
Sorry to have taken so long to look this over.  We had ambitions to integrate your content with the rest of HARK but have not found the time, so I'm just merging so other people can see/use it, and hope that we'll be able to integrate later.

**Comment by ganong123** [comment]
Works for us!

**Pull request merged**
