### PR TITLE
Documentation fix AMonninger

### PR DESCRIPTION
**Pull request by AMonninger**
Updating markdowns. Reshuffling and adding information to match the template. Template has additional comments to make it more user friendly.

To do:
-make sure information appears correctly in [econ-ark](https://econ-ark.org/materials)

Ready to review

### CODE REVIEW

**Comment by AMonninger** [comment]
@llorracc: Can someone review this?
I think it is ready to merge. After that I will check if everyhing works with econ-ark.org

**Comment by llorracc** [comment]
@AMonninger 

OK, merged.  Please check econ-ark.org.

**Comment by AMonninger** [comment]
@llorracc @MridulS : So far, the remarks haven't been updated on econ-ark.org. Is this something which only happens occasionally? Or do we need to do this manually?

**Comment by alanlujan91** [comment]
@MridulS, @llorracc and I thought that the econ-ark.org website had an action that is triggered by a change in any of the metadata in either DEMARK or REMARK but it does not seem to have picked up the changes that @AMonninger made and were merged a couple of days ago in this PR. Is this a bug or did we misunderstand? If the latter, how do we make econ-ark.org incorporate the new metadata?

**Pull request merged**
